"""initial schema

Revision ID: 47fe5f700800
Revises: 
Create Date: 2026-08-27 09:56:07.529844
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '47fe5f700800'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run',
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('department', sa.String(length=40), nullable=False),
    sa.Column('trigger', sa.String(length=60), nullable=False),
    sa.Column('trigger_ref', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'AWAITING_APPROVAL', 'COMPLETED', 'FAILED', 'REJECTED', name='agentrunstatus', native_enum=False, length=24), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thread_id', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_run'))
    )
    op.create_index('ix_agent_run_agent_date', 'agent_run', ['agent_name', 'business_date'], unique=False)
    op.create_index(op.f('ix_agent_run_agent_name'), 'agent_run', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_run_business_date'), 'agent_run', ['business_date'], unique=False)
    op.create_index(op.f('ix_agent_run_department'), 'agent_run', ['department'], unique=False)
    op.create_index(op.f('ix_agent_run_status'), 'agent_run', ['status'], unique=False)
    op.create_index(op.f('ix_agent_run_thread_id'), 'agent_run', ['thread_id'], unique=True)
    op.create_table('allergen',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allergen')),
    sa.UniqueConstraint('code', name=op.f('uq_allergen_code'))
    )
    op.create_table('bank_transaction',
    sa.Column('statement_ref', sa.String(length=80), nullable=False),
    sa.Column('posted_on', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('counterparty', sa.String(length=160), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_transaction')),
    sa.UniqueConstraint('statement_ref', name=op.f('uq_bank_transaction_statement_ref'))
    )
    op.create_index(op.f('ix_bank_transaction_is_reconciled'), 'bank_transaction', ['is_reconciled'], unique=False)
    op.create_index(op.f('ix_bank_transaction_posted_on'), 'bank_transaction', ['posted_on'], unique=False)
    op.create_table('campaign',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('objective', sa.String(length=200), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign')),
    sa.UniqueConstraint('name', name=op.f('uq_campaign_name'))
    )
    op.create_table('daily_report',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('net_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('covers', sa.Integer(), nullable=False),
    sa.Column('average_check', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cogs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('labour_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prime_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prime_cost_pct', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('labour_pct', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('food_cost_pct', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('operating_margin_pct', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('waste_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commentary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_report'))
    )
    op.create_index(op.f('ix_daily_report_business_date'), 'daily_report', ['business_date'], unique=True)
    op.create_table('delivery_payout',
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('payout_ref', sa.String(length=80), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('adjustments', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_payout', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_payout')),
    sa.UniqueConstraint('payout_ref', name=op.f('uq_delivery_payout_payout_ref'))
    )
    op.create_index(op.f('ix_delivery_payout_is_reconciled'), 'delivery_payout', ['is_reconciled'], unique=False)
    op.create_index(op.f('ix_delivery_payout_platform'), 'delivery_payout', ['platform'], unique=False)
    op.create_table('guest',
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('first_visit_on', sa.Date(), nullable=True),
    sa.Column('last_visit_on', sa.Date(), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('lifetime_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dietary_notes', sa.Text(), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest')),
    sa.UniqueConstraint('phone', name=op.f('uq_guest_phone'))
    )
    op.create_index(op.f('ix_guest_last_visit_on'), 'guest', ['last_visit_on'], unique=False)
    op.create_table('inbound_event',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_event')),
    sa.UniqueConstraint('provider', 'external_id', name='uq_inbound_event_provider_external')
    )
    op.create_index(op.f('ix_inbound_event_event_type'), 'inbound_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_inbound_event_provider'), 'inbound_event', ['provider'], unique=False)
    op.create_index(op.f('ix_inbound_event_received_at'), 'inbound_event', ['received_at'], unique=False)
    op.create_table('ingredient',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('base_uom', sa.String(length=12), nullable=False),
    sa.Column('cost_per_base_unit', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('yield_pct', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('allergen_codes', sa.String(length=300), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('yield_pct > 0 AND yield_pct <= 1', name=op.f('ck_ingredient_yield_pct_fraction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient'))
    )
    op.create_index(op.f('ix_ingredient_code'), 'ingredient', ['code'], unique=True)
    op.create_table('journal_entry',
    sa.Column('entry_number', sa.String(length=40), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('is_reversal_of', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['is_reversal_of'], ['journal_entry.id'], name=op.f('fk_journal_entry_is_reversal_of_journal_entry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entry'))
    )
    op.create_index(op.f('ix_journal_entry_business_date'), 'journal_entry', ['business_date'], unique=False)
    op.create_index(op.f('ix_journal_entry_entry_number'), 'journal_entry', ['entry_number'], unique=True)
    op.create_index(op.f('ix_journal_entry_source_id'), 'journal_entry', ['source_id'], unique=False)
    op.create_table('ledger_account',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_account'))
    )
    op.create_index(op.f('ix_ledger_account_code'), 'ledger_account', ['code'], unique=True)
    op.create_table('menu_section',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_section')),
    sa.UniqueConstraint('name', name=op.f('uq_menu_section_name'))
    )
    op.create_table('outbox_event',
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_event'))
    )
    op.create_index(op.f('ix_outbox_event_created_at'), 'outbox_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_event_dispatched_at'), 'outbox_event', ['dispatched_at'], unique=False)
    op.create_index(op.f('ix_outbox_event_source_run_id'), 'outbox_event', ['source_run_id'], unique=False)
    op.create_index(op.f('ix_outbox_event_topic'), 'outbox_event', ['topic'], unique=False)
    op.create_table('prep_plan',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('forecast_covers', sa.Integer(), nullable=False),
    sa.Column('forecast_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prep_plan'))
    )
    op.create_index(op.f('ix_prep_plan_business_date'), 'prep_plan', ['business_date'], unique=True)
    op.create_table('promo_offer',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('segment', sa.String(length=60), nullable=False),
    sa.Column('issued_count', sa.Integer(), nullable=False),
    sa.Column('redeemed_count', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_offer'))
    )
    op.create_index(op.f('ix_promo_offer_code'), 'promo_offer', ['code'], unique=True)
    op.create_table('reconciliation_batch',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('pos_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('card_settled', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cash_counted', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_count', sa.Integer(), nullable=False),
    sa.Column('is_balanced', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_batch'))
    )
    op.create_index(op.f('ix_reconciliation_batch_business_date'), 'reconciliation_batch', ['business_date'], unique=True)
    op.create_index(op.f('ix_reconciliation_batch_run_id'), 'reconciliation_batch', ['run_id'], unique=False)
    op.create_table('review',
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('author', sa.String(length=160), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='reviewsentiment', native_enum=False, length=16), nullable=True),
    sa.Column('topics', sa.String(length=300), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_escalated', sa.Boolean(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review')),
    sa.UniqueConstraint('platform', 'external_id', name='uq_review_platform_external')
    )
    op.create_index(op.f('ix_review_business_date'), 'review', ['business_date'], unique=False)
    op.create_index(op.f('ix_review_is_escalated'), 'review', ['is_escalated'], unique=False)
    op.create_index(op.f('ix_review_platform'), 'review', ['platform'], unique=False)
    op.create_index(op.f('ix_review_posted_at'), 'review', ['posted_at'], unique=False)
    op.create_index(op.f('ix_review_rating'), 'review', ['rating'], unique=False)
    op.create_index('ix_review_rating_date', 'review', ['rating', 'business_date'], unique=False)
    op.create_table('shift',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('role', sa.Enum('CHEF', 'LINE_COOK', 'KITCHEN_PORTER', 'SERVER', 'HOST', 'BARISTA', 'MANAGER', name='shiftrole', native_enum=False, length=24), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('required_headcount', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_shift_shift_window_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift'))
    )
    op.create_index(op.f('ix_shift_business_date'), 'shift', ['business_date'], unique=False)
    op.create_index('ix_shift_date_role', 'shift', ['business_date', 'role'], unique=False)
    op.create_index(op.f('ix_shift_run_id'), 'shift', ['run_id'], unique=False)
    op.create_table('sop_document',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('applies_to_role', sa.String(length=24), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sop_document'))
    )
    op.create_index(op.f('ix_sop_document_category'), 'sop_document', ['category'], unique=False)
    op.create_index(op.f('ix_sop_document_slug'), 'sop_document', ['slug'], unique=True)
    op.create_table('staff',
    sa.Column('employee_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('CHEF', 'LINE_COOK', 'KITCHEN_PORTER', 'SERVER', 'HOST', 'BARISTA', 'MANAGER', name='shiftrole', native_enum=False, length=24), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_weekly_hours', sa.Integer(), nullable=False),
    sa.Column('min_rest_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hourly_rate >= 0', name=op.f('ck_staff_hourly_rate_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff'))
    )
    op.create_index(op.f('ix_staff_employee_code'), 'staff', ['employee_code'], unique=True)
    op.create_index(op.f('ix_staff_role'), 'staff', ['role'], unique=False)
    op.create_table('supplier',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('min_order_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_days', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier'))
    )
    op.create_index(op.f('ix_supplier_code'), 'supplier', ['code'], unique=True)
    op.create_table('table_def',
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('min_party', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('is_combinable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('seats > 0', name=op.f('ck_table_def_seats_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table_def')),
    sa.UniqueConstraint('label', name=op.f('uq_table_def_label'))
    )
    op.create_table('agent_action',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_proposal', sa.Boolean(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], name=op.f('fk_agent_action_run_id_agent_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_action'))
    )
    op.create_index(op.f('ix_agent_action_run_id'), 'agent_action', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_action_tool_name'), 'agent_action', ['tool_name'], unique=False)
    op.create_table('approval_request',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=80), nullable=False),
    sa.Column('agent_name', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approvalstatus', native_enum=False, length=16), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('channel_message_ref', sa.String(length=120), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], name=op.f('fk_approval_request_run_id_agent_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_request'))
    )
    op.create_index(op.f('ix_approval_request_agent_name'), 'approval_request', ['agent_name'], unique=False)
    op.create_index(op.f('ix_approval_request_run_id'), 'approval_request', ['run_id'], unique=False)
    op.create_index(op.f('ix_approval_request_status'), 'approval_request', ['status'], unique=False)
    op.create_index(op.f('ix_approval_request_thread_id'), 'approval_request', ['thread_id'], unique=False)
    op.create_table('availability',
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_availability_window_ordered')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_availability_weekday_range')),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_availability_staff_id_staff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability')),
    sa.UniqueConstraint('staff_id', 'weekday', 'start_time', name='uq_availability_slot')
    )
    op.create_index(op.f('ix_availability_staff_id'), 'availability', ['staff_id'], unique=False)
    op.create_table('journal_line',
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('memo', sa.String(length=240), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('(debit = 0) <> (credit = 0)', name=op.f('ck_journal_line_one_sided')),
    sa.CheckConstraint('debit >= 0 AND credit >= 0', name=op.f('ck_journal_line_non_negative')),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_account.id'], name=op.f('fk_journal_line_account_id_ledger_account')),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entry.id'], name=op.f('fk_journal_line_entry_id_journal_entry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_line'))
    )
    op.create_index('ix_journal_line_account_entry', 'journal_line', ['account_id', 'entry_id'], unique=False)
    op.create_index(op.f('ix_journal_line_account_id'), 'journal_line', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_line_entry_id'), 'journal_line', ['entry_id'], unique=False)
    op.create_table('menu_item',
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('station', sa.Enum('GRILL', 'FRY', 'SAUTE', 'COLD', 'PASTRY', 'BAR', 'EXPO', name='station', native_enum=False, length=20), nullable=False),
    sa.Column('prep_seconds', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('menu_class', sa.Enum('STAR', 'PLOWHORSE', 'PUZZLE', 'DOG', name='menuclass', native_enum=False, length=20), nullable=True),
    sa.Column('last_price_change_on', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_menu_item_price_non_negative')),
    sa.ForeignKeyConstraint(['section_id'], ['menu_section.id'], name=op.f('fk_menu_item_section_id_menu_section')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item'))
    )
    op.create_index(op.f('ix_menu_item_sku'), 'menu_item', ['sku'], unique=True)
    op.create_table('order_header',
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.Enum('DINE_IN', 'TAKEAWAY', 'DRIVE_THRU', 'DELIVERY', 'KIOSK', 'PHONE', name='orderchannel', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FIRED', 'SERVED', 'CLOSED', 'VOID', name='orderstatus', native_enum=False, length=20), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=True),
    sa.Column('guest_id', sa.String(length=36), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_platform', sa.String(length=40), nullable=True),
    sa.Column('external_ref', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], name=op.f('fk_order_header_guest_id_guest')),
    sa.ForeignKeyConstraint(['table_id'], ['table_def.id'], name=op.f('fk_order_header_table_id_table_def')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_header'))
    )
    op.create_index(op.f('ix_order_header_business_date'), 'order_header', ['business_date'], unique=False)
    op.create_index(op.f('ix_order_header_channel'), 'order_header', ['channel'], unique=False)
    op.create_index('ix_order_header_date_channel', 'order_header', ['business_date', 'channel'], unique=False)
    op.create_index(op.f('ix_order_header_delivery_platform'), 'order_header', ['delivery_platform'], unique=False)
    op.create_index(op.f('ix_order_header_guest_id'), 'order_header', ['guest_id'], unique=False)
    op.create_index(op.f('ix_order_header_order_number'), 'order_header', ['order_number'], unique=True)
    op.create_index(op.f('ix_order_header_placed_at'), 'order_header', ['placed_at'], unique=False)
    op.create_index(op.f('ix_order_header_status'), 'order_header', ['status'], unique=False)
    op.create_table('prep_plan_line',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('forecast_usage', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('prep_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=12), nullable=False),
    sa.Column('on_hand_at_plan', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('actual_usage', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_prep_plan_line_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['plan_id'], ['prep_plan.id'], name=op.f('fk_prep_plan_line_plan_id_prep_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prep_plan_line'))
    )
    op.create_index(op.f('ix_prep_plan_line_ingredient_id'), 'prep_plan_line', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_prep_plan_line_plan_id'), 'prep_plan_line', ['plan_id'], unique=False)
    op.create_table('purchase_order',
    sa.Column('po_number', sa.String(length=40), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', 'REJECTED', name='purchaseorderstatus', native_enum=False, length=24), nullable=False),
    sa.Column('expected_delivery_on', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_by_run_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_purchase_order_supplier_id_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order'))
    )
    op.create_index(op.f('ix_purchase_order_created_by_run_id'), 'purchase_order', ['created_by_run_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_po_number'), 'purchase_order', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_order_status'), 'purchase_order', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_order_supplier_id'), 'purchase_order', ['supplier_id'], unique=False)
    op.create_table('reconciliation_match',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('left_type', sa.String(length=40), nullable=False),
    sa.Column('left_id', sa.String(length=36), nullable=False),
    sa.Column('right_type', sa.String(length=40), nullable=True),
    sa.Column('right_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_exception', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=240), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['reconciliation_batch.id'], name=op.f('fk_reconciliation_match_batch_id_reconciliation_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_match'))
    )
    op.create_index(op.f('ix_reconciliation_match_batch_id'), 'reconciliation_match', ['batch_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_is_exception'), 'reconciliation_match', ['is_exception'], unique=False)
    op.create_table('reorder_policy',
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('safety_stock', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('target_days_cover', sa.Integer(), nullable=False),
    sa.Column('avg_daily_usage', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('usage_stddev', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_reorder_policy_ingredient_id_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reorder_policy')),
    sa.UniqueConstraint('ingredient_id', name=op.f('uq_reorder_policy_ingredient_id'))
    )
    op.create_table('reservation',
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('guest_id', sa.String(length=36), nullable=True),
    sa.Column('guest_name', sa.String(length=160), nullable=False),
    sa.Column('guest_phone', sa.String(length=40), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'SEATED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='reservationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('party_size > 0', name=op.f('ck_reservation_party_size_positive')),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], name=op.f('fk_reservation_guest_id_guest')),
    sa.ForeignKeyConstraint(['table_id'], ['table_def.id'], name=op.f('fk_reservation_table_id_table_def')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservation'))
    )
    op.create_index(op.f('ix_reservation_business_date'), 'reservation', ['business_date'], unique=False)
    op.create_index(op.f('ix_reservation_guest_id'), 'reservation', ['guest_id'], unique=False)
    op.create_index(op.f('ix_reservation_reference'), 'reservation', ['reference'], unique=True)
    op.create_index(op.f('ix_reservation_starts_at'), 'reservation', ['starts_at'], unique=False)
    op.create_index(op.f('ix_reservation_status'), 'reservation', ['status'], unique=False)
    op.create_index(op.f('ix_reservation_table_id'), 'reservation', ['table_id'], unique=False)
    op.create_index('ix_reservation_table_window', 'reservation', ['table_id', 'starts_at', 'expected_end_at'], unique=False)
    op.create_table('shift_assignment',
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('swap_requested_with', sa.String(length=36), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('fk_shift_assignment_shift_id_shift')),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_shift_assignment_staff_id_staff')),
    sa.ForeignKeyConstraint(['swap_requested_with'], ['staff.id'], name=op.f('fk_shift_assignment_swap_requested_with_staff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_assignment')),
    sa.UniqueConstraint('shift_id', 'staff_id', name='uq_shift_assignment')
    )
    op.create_index(op.f('ix_shift_assignment_shift_id'), 'shift_assignment', ['shift_id'], unique=False)
    op.create_index(op.f('ix_shift_assignment_staff_id'), 'shift_assignment', ['staff_id'], unique=False)
    op.create_table('stock_item',
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_sku', sa.String(length=60), nullable=False),
    sa.Column('pack_size', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('pack_uom', sa.String(length=12), nullable=False),
    sa.Column('contract_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_order_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pack_size > 0', name=op.f('ck_stock_item_pack_size_positive')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_stock_item_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_stock_item_supplier_id_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_item')),
    sa.UniqueConstraint('supplier_id', 'supplier_sku', name='uq_stock_item_supplier_sku')
    )
    op.create_index(op.f('ix_stock_item_ingredient_id'), 'stock_item', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_stock_item_supplier_id'), 'stock_item', ['supplier_id'], unique=False)
    op.create_table('stock_movement',
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reason', sa.Enum('SALE', 'RECEIPT', 'WASTE', 'COUNT_ADJUSTMENT', 'TRANSFER', 'PREP', name='movementreason', native_enum=False, length=24), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('quantity <> 0', name=op.f('ck_stock_movement_quantity_non_zero')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_stock_movement_ingredient_id_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movement'))
    )
    op.create_index(op.f('ix_stock_movement_ingredient_id'), 'stock_movement', ['ingredient_id'], unique=False)
    op.create_index('ix_stock_movement_ingredient_time', 'stock_movement', ['ingredient_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_stock_movement_occurred_at'), 'stock_movement', ['occurred_at'], unique=False)
    op.create_table('time_entry',
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_time_entry_staff_id_staff')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_entry'))
    )
    op.create_index(op.f('ix_time_entry_business_date'), 'time_entry', ['business_date'], unique=False)
    op.create_index(op.f('ix_time_entry_staff_id'), 'time_entry', ['staff_id'], unique=False)
    op.create_table('uom_conversion',
    sa.Column('from_uom', sa.String(length=12), nullable=False),
    sa.Column('to_uom', sa.String(length=12), nullable=False),
    sa.Column('factor', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('factor > 0', name=op.f('ck_uom_conversion_factor_positive')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_uom_conversion_ingredient_id_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uom_conversion')),
    sa.UniqueConstraint('from_uom', 'to_uom', 'ingredient_id', name='uq_uom_conversion_triple')
    )
    op.create_table('goods_receipt',
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_by', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('fk_goods_receipt_purchase_order_id_purchase_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt'))
    )
    op.create_index(op.f('ix_goods_receipt_purchase_order_id'), 'goods_receipt', ['purchase_order_id'], unique=False)
    op.create_table('item_forecast',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('forecast_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('actual_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('abs_error', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_item_forecast_menu_item_id_menu_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_forecast')),
    sa.UniqueConstraint('business_date', 'menu_item_id', name='uq_item_forecast_date_item')
    )
    op.create_index(op.f('ix_item_forecast_business_date'), 'item_forecast', ['business_date'], unique=False)
    op.create_index(op.f('ix_item_forecast_menu_item_id'), 'item_forecast', ['menu_item_id'], unique=False)
    op.create_table('menu_item_price_history',
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_menu_item_price_history_menu_item_id_menu_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_price_history'))
    )
    op.create_index(op.f('ix_menu_item_price_history_menu_item_id'), 'menu_item_price_history', ['menu_item_id'], unique=False)
    op.create_table('order_line',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('modifiers', sa.Text(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('is_voided', sa.Boolean(), nullable=False),
    sa.Column('stock_deducted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_line_quantity_positive')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_order_line_menu_item_id_menu_item')),
    sa.ForeignKeyConstraint(['order_id'], ['order_header.id'], name=op.f('fk_order_line_order_id_order_header')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_line'))
    )
    op.create_index(op.f('ix_order_line_menu_item_id'), 'order_line', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_order_line_order_id'), 'order_line', ['order_id'], unique=False)
    op.create_table('payment',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'CARD', 'EWALLET', 'DELIVERY_PLATFORM', 'VOUCHER', name='paymentmethod', native_enum=False, length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tip', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('processor_ref', sa.String(length=80), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_header.id'], name=op.f('fk_payment_order_id_order_header')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.create_index(op.f('ix_payment_business_date'), 'payment', ['business_date'], unique=False)
    op.create_index(op.f('ix_payment_is_reconciled'), 'payment', ['is_reconciled'], unique=False)
    op.create_index(op.f('ix_payment_method'), 'payment', ['method'], unique=False)
    op.create_index(op.f('ix_payment_order_id'), 'payment', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_paid_at'), 'payment', ['paid_at'], unique=False)
    op.create_index(op.f('ix_payment_processor_ref'), 'payment', ['processor_ref'], unique=False)
    op.create_table('purchase_order_line',
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('stock_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_packs', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('received_packs', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('quantity_packs > 0', name=op.f('ck_purchase_order_line_quantity_packs_positive')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('fk_purchase_order_line_purchase_order_id_purchase_order')),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_item.id'], name=op.f('fk_purchase_order_line_stock_item_id_stock_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_line'))
    )
    op.create_index(op.f('ix_purchase_order_line_purchase_order_id'), 'purchase_order_line', ['purchase_order_id'], unique=False)
    op.create_table('recipe',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('menu_item_id', sa.String(length=36), nullable=True),
    sa.Column('yield_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('yield_uom', sa.String(length=12), nullable=False),
    sa.Column('station', sa.Enum('GRILL', 'FRY', 'SAUTE', 'COLD', 'PASTRY', 'BAR', 'EXPO', name='station', native_enum=False, length=20), nullable=False),
    sa.Column('prep_seconds', sa.Integer(), nullable=False),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('yield_qty > 0', name=op.f('ck_recipe_yield_qty_positive')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('fk_recipe_menu_item_id_menu_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe')),
    sa.UniqueConstraint('menu_item_id', name=op.f('uq_recipe_menu_item_id'))
    )
    op.create_index(op.f('ix_recipe_code'), 'recipe', ['code'], unique=True)
    op.create_table('seating_event',
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('seated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_header.id'], name=op.f('fk_seating_event_order_id_order_header')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], name=op.f('fk_seating_event_reservation_id_reservation')),
    sa.ForeignKeyConstraint(['table_id'], ['table_def.id'], name=op.f('fk_seating_event_table_id_table_def')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seating_event'))
    )
    op.create_index(op.f('ix_seating_event_business_date'), 'seating_event', ['business_date'], unique=False)
    op.create_index(op.f('ix_seating_event_seated_at'), 'seating_event', ['seated_at'], unique=False)
    op.create_index(op.f('ix_seating_event_table_id'), 'seating_event', ['table_id'], unique=False)
    op.create_table('social_post',
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_ref', sa.String(length=80), nullable=True),
    sa.Column('featured_menu_item_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_social_post_campaign_id_campaign')),
    sa.ForeignKeyConstraint(['featured_menu_item_id'], ['menu_item.id'], name=op.f('fk_social_post_featured_menu_item_id_menu_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_post'))
    )
    op.create_index(op.f('ix_social_post_campaign_id'), 'social_post', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_social_post_platform'), 'social_post', ['platform'], unique=False)
    op.create_index(op.f('ix_social_post_run_id'), 'social_post', ['run_id'], unique=False)
    op.create_index(op.f('ix_social_post_scheduled_for'), 'social_post', ['scheduled_for'], unique=False)
    op.create_table('supplier_invoice',
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'MATCHED', 'DISPUTED', 'APPROVED_FOR_PAYMENT', 'PAID', name='invoicestatus', native_enum=False, length=24), nullable=False),
    sa.Column('document_uri', sa.String(length=400), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('fk_supplier_invoice_purchase_order_id_purchase_order')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_invoice_supplier_id_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_invoice')),
    sa.UniqueConstraint('supplier_id', 'invoice_number', name='uq_supplier_invoice_number')
    )
    op.create_index(op.f('ix_supplier_invoice_invoice_number'), 'supplier_invoice', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_supplier_invoice_status'), 'supplier_invoice', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_invoice_supplier_id'), 'supplier_invoice', ['supplier_id'], unique=False)
    op.create_table('goods_receipt_line',
    sa.Column('goods_receipt_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_line_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_packs', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], name=op.f('fk_goods_receipt_line_goods_receipt_id_goods_receipt')),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_line.id'], name=op.f('fk_goods_receipt_line_purchase_order_line_id_purchase_order_line')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt_line'))
    )
    op.create_index(op.f('ix_goods_receipt_line_goods_receipt_id'), 'goods_receipt_line', ['goods_receipt_id'], unique=False)
    op.create_table('kds_ticket',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('order_line_id', sa.String(length=36), nullable=False),
    sa.Column('station', sa.Enum('GRILL', 'FRY', 'SAUTE', 'COLD', 'PASTRY', 'BAR', 'EXPO', name='station', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'READY', 'SERVED', name='ticketstatus', native_enum=False, length=20), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modifiers', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_header.id'], name=op.f('fk_kds_ticket_order_id_order_header')),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_line.id'], name=op.f('fk_kds_ticket_order_line_id_order_line')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kds_ticket'))
    )
    op.create_index(op.f('ix_kds_ticket_fire_at'), 'kds_ticket', ['fire_at'], unique=False)
    op.create_index(op.f('ix_kds_ticket_order_id'), 'kds_ticket', ['order_id'], unique=False)
    op.create_index(op.f('ix_kds_ticket_order_line_id'), 'kds_ticket', ['order_line_id'], unique=False)
    op.create_index(op.f('ix_kds_ticket_station'), 'kds_ticket', ['station'], unique=False)
    op.create_index('ix_kds_ticket_station_fire', 'kds_ticket', ['station', 'fire_at'], unique=False)
    op.create_index(op.f('ix_kds_ticket_status'), 'kds_ticket', ['status'], unique=False)
    op.create_table('recipe_component',
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=True),
    sa.Column('sub_recipe_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=12), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('(ingredient_id IS NOT NULL) <> (sub_recipe_id IS NOT NULL)', name=op.f('ck_recipe_component_exactly_one_target')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_recipe_component_quantity_positive')),
    sa.CheckConstraint('sub_recipe_id IS NULL OR sub_recipe_id <> recipe_id', name=op.f('ck_recipe_component_no_self_ref')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_recipe_component_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_component_recipe_id_recipe')),
    sa.ForeignKeyConstraint(['sub_recipe_id'], ['recipe.id'], name=op.f('fk_recipe_component_sub_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_component'))
    )
    op.create_index(op.f('ix_recipe_component_recipe_id'), 'recipe_component', ['recipe_id'], unique=False)
    op.create_index('ix_recipe_component_recipe_ingredient', 'recipe_component', ['recipe_id', 'ingredient_id'], unique=False)
    op.create_table('supplier_invoice_line',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('stock_item_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('quantity_packs', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['supplier_invoice.id'], name=op.f('fk_supplier_invoice_line_invoice_id_supplier_invoice')),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_item.id'], name=op.f('fk_supplier_invoice_line_stock_item_id_stock_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_invoice_line'))
    )
    op.create_index(op.f('ix_supplier_invoice_line_invoice_id'), 'supplier_invoice_line', ['invoice_id'], unique=False)
    op.create_table('invoice_discrepancy',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_line_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('PRICE', 'QUANTITY', 'TAX', 'MISSING_LINE', 'UNEXPECTED_LINE', name='discrepancykind', native_enum=False, length=24), nullable=False),
    sa.Column('expected', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['supplier_invoice.id'], name=op.f('fk_invoice_discrepancy_invoice_id_supplier_invoice')),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['supplier_invoice_line.id'], name=op.f('fk_invoice_discrepancy_invoice_line_id_supplier_invoice_line')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_discrepancy'))
    )
    op.create_index(op.f('ix_invoice_discrepancy_invoice_id'), 'invoice_discrepancy', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_discrepancy_invoice_id'), table_name='invoice_discrepancy')
    op.drop_table('invoice_discrepancy')
    op.drop_index(op.f('ix_supplier_invoice_line_invoice_id'), table_name='supplier_invoice_line')
    op.drop_table('supplier_invoice_line')
    op.drop_index('ix_recipe_component_recipe_ingredient', table_name='recipe_component')
    op.drop_index(op.f('ix_recipe_component_recipe_id'), table_name='recipe_component')
    op.drop_table('recipe_component')
    op.drop_index(op.f('ix_kds_ticket_status'), table_name='kds_ticket')
    op.drop_index('ix_kds_ticket_station_fire', table_name='kds_ticket')
    op.drop_index(op.f('ix_kds_ticket_station'), table_name='kds_ticket')
    op.drop_index(op.f('ix_kds_ticket_order_line_id'), table_name='kds_ticket')
    op.drop_index(op.f('ix_kds_ticket_order_id'), table_name='kds_ticket')
    op.drop_index(op.f('ix_kds_ticket_fire_at'), table_name='kds_ticket')
    op.drop_table('kds_ticket')
    op.drop_index(op.f('ix_goods_receipt_line_goods_receipt_id'), table_name='goods_receipt_line')
    op.drop_table('goods_receipt_line')
    op.drop_index(op.f('ix_supplier_invoice_supplier_id'), table_name='supplier_invoice')
    op.drop_index(op.f('ix_supplier_invoice_status'), table_name='supplier_invoice')
    op.drop_index(op.f('ix_supplier_invoice_invoice_number'), table_name='supplier_invoice')
    op.drop_table('supplier_invoice')
    op.drop_index(op.f('ix_social_post_scheduled_for'), table_name='social_post')
    op.drop_index(op.f('ix_social_post_run_id'), table_name='social_post')
    op.drop_index(op.f('ix_social_post_platform'), table_name='social_post')
    op.drop_index(op.f('ix_social_post_campaign_id'), table_name='social_post')
    op.drop_table('social_post')
    op.drop_index(op.f('ix_seating_event_table_id'), table_name='seating_event')
    op.drop_index(op.f('ix_seating_event_seated_at'), table_name='seating_event')
    op.drop_index(op.f('ix_seating_event_business_date'), table_name='seating_event')
    op.drop_table('seating_event')
    op.drop_index(op.f('ix_recipe_code'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_purchase_order_line_purchase_order_id'), table_name='purchase_order_line')
    op.drop_table('purchase_order_line')
    op.drop_index(op.f('ix_payment_processor_ref'), table_name='payment')
    op.drop_index(op.f('ix_payment_paid_at'), table_name='payment')
    op.drop_index(op.f('ix_payment_order_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_method'), table_name='payment')
    op.drop_index(op.f('ix_payment_is_reconciled'), table_name='payment')
    op.drop_index(op.f('ix_payment_business_date'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_order_line_order_id'), table_name='order_line')
    op.drop_index(op.f('ix_order_line_menu_item_id'), table_name='order_line')
    op.drop_table('order_line')
    op.drop_index(op.f('ix_menu_item_price_history_menu_item_id'), table_name='menu_item_price_history')
    op.drop_table('menu_item_price_history')
    op.drop_index(op.f('ix_item_forecast_menu_item_id'), table_name='item_forecast')
    op.drop_index(op.f('ix_item_forecast_business_date'), table_name='item_forecast')
    op.drop_table('item_forecast')
    op.drop_index(op.f('ix_goods_receipt_purchase_order_id'), table_name='goods_receipt')
    op.drop_table('goods_receipt')
    op.drop_table('uom_conversion')
    op.drop_index(op.f('ix_time_entry_staff_id'), table_name='time_entry')
    op.drop_index(op.f('ix_time_entry_business_date'), table_name='time_entry')
    op.drop_table('time_entry')
    op.drop_index(op.f('ix_stock_movement_occurred_at'), table_name='stock_movement')
    op.drop_index('ix_stock_movement_ingredient_time', table_name='stock_movement')
    op.drop_index(op.f('ix_stock_movement_ingredient_id'), table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_index(op.f('ix_stock_item_supplier_id'), table_name='stock_item')
    op.drop_index(op.f('ix_stock_item_ingredient_id'), table_name='stock_item')
    op.drop_table('stock_item')
    op.drop_index(op.f('ix_shift_assignment_staff_id'), table_name='shift_assignment')
    op.drop_index(op.f('ix_shift_assignment_shift_id'), table_name='shift_assignment')
    op.drop_table('shift_assignment')
    op.drop_index('ix_reservation_table_window', table_name='reservation')
    op.drop_index(op.f('ix_reservation_table_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_status'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_starts_at'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_reference'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_guest_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_business_date'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_table('reorder_policy')
    op.drop_index(op.f('ix_reconciliation_match_is_exception'), table_name='reconciliation_match')
    op.drop_index(op.f('ix_reconciliation_match_batch_id'), table_name='reconciliation_match')
    op.drop_table('reconciliation_match')
    op.drop_index(op.f('ix_purchase_order_supplier_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_status'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_po_number'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_created_by_run_id'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_prep_plan_line_plan_id'), table_name='prep_plan_line')
    op.drop_index(op.f('ix_prep_plan_line_ingredient_id'), table_name='prep_plan_line')
    op.drop_table('prep_plan_line')
    op.drop_index(op.f('ix_order_header_status'), table_name='order_header')
    op.drop_index(op.f('ix_order_header_placed_at'), table_name='order_header')
    op.drop_index(op.f('ix_order_header_order_number'), table_name='order_header')
    op.drop_index(op.f('ix_order_header_guest_id'), table_name='order_header')
    op.drop_index(op.f('ix_order_header_delivery_platform'), table_name='order_header')
    op.drop_index('ix_order_header_date_channel', table_name='order_header')
    op.drop_index(op.f('ix_order_header_channel'), table_name='order_header')
    op.drop_index(op.f('ix_order_header_business_date'), table_name='order_header')
    op.drop_table('order_header')
    op.drop_index(op.f('ix_menu_item_sku'), table_name='menu_item')
    op.drop_table('menu_item')
    op.drop_index(op.f('ix_journal_line_entry_id'), table_name='journal_line')
    op.drop_index(op.f('ix_journal_line_account_id'), table_name='journal_line')
    op.drop_index('ix_journal_line_account_entry', table_name='journal_line')
    op.drop_table('journal_line')
    op.drop_index(op.f('ix_availability_staff_id'), table_name='availability')
    op.drop_table('availability')
    op.drop_index(op.f('ix_approval_request_thread_id'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_status'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_run_id'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_agent_name'), table_name='approval_request')
    op.drop_table('approval_request')
    op.drop_index(op.f('ix_agent_action_tool_name'), table_name='agent_action')
    op.drop_index(op.f('ix_agent_action_run_id'), table_name='agent_action')
    op.drop_table('agent_action')
    op.drop_table('table_def')
    op.drop_index(op.f('ix_supplier_code'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_staff_role'), table_name='staff')
    op.drop_index(op.f('ix_staff_employee_code'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_sop_document_slug'), table_name='sop_document')
    op.drop_index(op.f('ix_sop_document_category'), table_name='sop_document')
    op.drop_table('sop_document')
    op.drop_index(op.f('ix_shift_run_id'), table_name='shift')
    op.drop_index('ix_shift_date_role', table_name='shift')
    op.drop_index(op.f('ix_shift_business_date'), table_name='shift')
    op.drop_table('shift')
    op.drop_index('ix_review_rating_date', table_name='review')
    op.drop_index(op.f('ix_review_rating'), table_name='review')
    op.drop_index(op.f('ix_review_posted_at'), table_name='review')
    op.drop_index(op.f('ix_review_platform'), table_name='review')
    op.drop_index(op.f('ix_review_is_escalated'), table_name='review')
    op.drop_index(op.f('ix_review_business_date'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_reconciliation_batch_run_id'), table_name='reconciliation_batch')
    op.drop_index(op.f('ix_reconciliation_batch_business_date'), table_name='reconciliation_batch')
    op.drop_table('reconciliation_batch')
    op.drop_index(op.f('ix_promo_offer_code'), table_name='promo_offer')
    op.drop_table('promo_offer')
    op.drop_index(op.f('ix_prep_plan_business_date'), table_name='prep_plan')
    op.drop_table('prep_plan')
    op.drop_index(op.f('ix_outbox_event_topic'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_source_run_id'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_dispatched_at'), table_name='outbox_event')
    op.drop_index(op.f('ix_outbox_event_created_at'), table_name='outbox_event')
    op.drop_table('outbox_event')
    op.drop_table('menu_section')
    op.drop_index(op.f('ix_ledger_account_code'), table_name='ledger_account')
    op.drop_table('ledger_account')
    op.drop_index(op.f('ix_journal_entry_source_id'), table_name='journal_entry')
    op.drop_index(op.f('ix_journal_entry_entry_number'), table_name='journal_entry')
    op.drop_index(op.f('ix_journal_entry_business_date'), table_name='journal_entry')
    op.drop_table('journal_entry')
    op.drop_index(op.f('ix_ingredient_code'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_inbound_event_received_at'), table_name='inbound_event')
    op.drop_index(op.f('ix_inbound_event_provider'), table_name='inbound_event')
    op.drop_index(op.f('ix_inbound_event_event_type'), table_name='inbound_event')
    op.drop_table('inbound_event')
    op.drop_index(op.f('ix_guest_last_visit_on'), table_name='guest')
    op.drop_table('guest')
    op.drop_index(op.f('ix_delivery_payout_platform'), table_name='delivery_payout')
    op.drop_index(op.f('ix_delivery_payout_is_reconciled'), table_name='delivery_payout')
    op.drop_table('delivery_payout')
    op.drop_index(op.f('ix_daily_report_business_date'), table_name='daily_report')
    op.drop_table('daily_report')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_bank_transaction_posted_on'), table_name='bank_transaction')
    op.drop_index(op.f('ix_bank_transaction_is_reconciled'), table_name='bank_transaction')
    op.drop_table('bank_transaction')
    op.drop_table('allergen')
    op.drop_index(op.f('ix_agent_run_thread_id'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_status'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_department'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_business_date'), table_name='agent_run')
    op.drop_index(op.f('ix_agent_run_agent_name'), table_name='agent_run')
    op.drop_index('ix_agent_run_agent_date', table_name='agent_run')
    op.drop_table('agent_run')
    # ### end Alembic commands ###
